### PR TITLE
Updated the mod.cg file in src/data/buildcraft & also renamed the 6.2.6 folder to 6.3.4.

### PR DESCRIPTION
**Pull request by KamranMackey**
The commits & title says it all. I'll work on updating the mod-version.cg file in a little bit.

### CODE REVIEW

**Comment by andrewminer** [comment]
Thanks, Kamran!  I'll hold off on merging until everything is updated.

**Comment by KamranMackey** [comment]
Okay, but I have a question. How do I figure out the patterns for the items? Because that part kind of confuses me a little.

**Comment by KamranMackey** [comment]
@andrewminer Okay, but I have a question. How do I figure out the patterns for the items? Because that part kind of confuses me a little.

**Comment by andrewminer** [comment]
I use NEI to pull up the recipes.  I use the "NEI Subsets" and right-click on the "Mods" section, and then click on the mod I want (e.g., BuildCraft).  That will limit the item panel to just those items for that mod.  From there, you can hover your mouse of any item, press "R" and see the recipe.

In this case, though, I doubt very much if there's any substantial changes between version 6.2.6 and 6.3.4, so re-doing all the recipes is probably not necessary.  I'd start by checking the change log for Buildcraft and seeing what they say they've added/removed/changed and just focus on that.

To be honest, it's quite possible there are no new items or recipe changes to add.  If you're eager to help out, might I suggest you try adding support for a new mod?  You can follow [these instructions](https://github.com/andrewminer/crafting-guide/wiki/Adding-support-for-a-new-Mod) to put everything together.  People have been asking for [Forestry](http://forestry.sengir.net/wiki.new/doku.php), so you might like to start with that.  :-)

**Comment by KamranMackey** [comment]
@andrewminer This is what 6.3 of BuildCraft added (fetched from the blog):

> Additions:

> Lenses! Crafted from an iron ingot, a dye and a piece of glass in an Assembly Table, they are used to color items passing through them on pipes. (asie)
Yes, you can stick them on the sides of pipes. Fancy!
Filters! Replace an iron ingot with a bar in the lens recipe to filter items passing through by color.
Facade rework: hollow facades are now explicit, separate items, craftable in the Assembly Table. (You can also turn existing regular facades to hollow facades and back.) (asie)
More machines can now be controlled with gate actions (asie)
Lapis and Daizuli pipes can have their colour set with a dye (asie)
Multiple pulses with Autarchic Pulsars are now back (asie)
Quartz Gates! Inbetween Iron and Emerald gates, they contain 2 trigger/action sets with 1 parameter for each! (asie)
Fuel energy production rate config option (marcin212)
Gate and chipset recipe cost multiplier options for modpack developers (asie)
Gates and wires now glow in the dark when active (ganymedes01)
Pipe wires have a slightly improved texture (CyanideX)
GUI improvements:
You can now use the scrollwheel in Gates (to scroll through triggers and actions) and Zone Planners (to zoom in and out) (asie)
F5 now refreshes the zone planner map (asie)
Chutes can now be powered with Engines, much like wooden pipes, to extract items; however, they have a 10 RF/t cap (asie)

Sorry for the gigantic wall of text. :D

**Comment by KamranMackey** [comment]
So technically, all I need to add are the lenses, filters and quartz gates. But I'm still having some trouble figuring out how to figure out the patterns for those items.

**Comment by andrewminer** [comment]
Take a look at [this mod spotlight](https://www.youtube.com/watch?v=ppPtNRSKvqU) for NotEnoughItems (NEI).  It should help you get your head around how to navigate NEI.

**Comment by KamranMackey** [comment]
@andrewminer Watched it, but I still can't figure out how to figure out the patterns for those items. :disappointed:

**Comment by KamranMackey** [comment]
I know how to use Not Enough Items, but  I just don't know how to figure
out the patterns. How did you figure out the patterns? Maybe that might
help me figure out the patterns for when I get home from school. :smiley:

**Comment by KamranMackey** [comment]
@andrewminer  I know how to use Not Enough Items, but  I just don't know how to figure
out the patterns. How did you figure out the patterns? Maybe that might
help me figure out the patterns for when I get home from school. :smiley:

**Comment by KamranMackey** [comment]
@andrewminer  I know how to use Not Enough Items, but  I just don't know how to figure
out the patterns. How did you figure out the patterns? Maybe that might
help me figure out the patterns for when I get home from school. :smiley:

**Comment by andrewminer** [comment]
Perhaps I'm not understanding where you're getting stuck.  Are you saying you can find the recipe in NEI just fine, but you can't figure out how to translate that into the `pattern: 000 0.0 000` text?  If that's the case, check out the [Data Format Guide](https://github.com/andrewminer/crafting-guide/wiki/Crafting-Guide-Data-Format-V2)'s section on the "pattern" command.

**Comment by KamranMackey** [comment]
@andrewminer I just did, but I'm still having trouble understanding it. :disappointed:

**Comment by andrewminer** [comment]
Can you clarify your difficulty?  Did the examples in the documentation make sense?

**Comment by KamranMackey** [comment]
@andrewminer Yes they did make sense, but I don't know how to figure out the patterns for the Forestry items, blocks or tools. That's what I'm having trouble with. :disappointed:

**Comment by KamranMackey** [comment]
@andrewminer By the way, could you please merge the commits I made in this pull request? Because apparently the lenses that @asiekierka added in the BuildCraft 6.3 update aren't even craftable, according to Not Enough Items.

**Comment by asiekierka** [comment]
They should be. I saw people craft them on LPs

**Comment by KamranMackey** [comment]
@asiekierka Odd. NEI doesn't seem to think that they are on my end, because when I tried to craft them, NEI for some reason didn't show me the recipe, which is really weird.

**Comment by KamranMackey** [comment]
@andrewminer Yes they did make sense, but I don't know how to figure out the patterns for the Forestry items, blocks or tools. That's what I'm having trouble with. :disappointed: 

By the way, could you please merge the commits I made in this pull request?

**Comment by andrewminer** [comment]
@KamranMackey Sorry, Kamran, I can't merge the changes since they aren't complete (i.e., it says version 6.3.4 without actually having all the stuff for that version).

If you'd like to describe the steps you've taken so far, and at what point you got stuck, I might be able to help, but as it stands I'm not sure what more I can do for you.

**Comment by KamranMackey** [comment]
That's because that version adds nothing but bug fixes.

On Sat, Feb 7, 2015 at 2:14 PM, Andrew Miner <notifications@github.com>
wrote:

> @KamranMackey <https://github.com/KamranMackey> Sorry, Kamran, I can't
> merge the changes since they aren't complete (i.e., it says version 6.3.4
> without actually having all the stuff for that version).
>
> If you'd like to describe the steps you've taken so far, and at what point
> you got stuck, I might be able to help, but as it stands I'm not sure what
> more I can do for you.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewminer/crafting-guide/pull/43#issuecomment-73383447>
> .
>



-- 
- Kamran Mackey

**Comment by andrewminer** [comment]
I'm confused, then.  The change list you added to this comment thread seemed to clearly talk about new items added to the game (e.g., lenses and filters).

**Comment by KamranMackey** [comment]
Andrew, that was for the original version of 6.3. not 6.3.4. And anyway my
pull request is out of date now that BC 6.3.6 is out now anyway.

On Sat, Feb 7, 2015 at 11:12 PM, Andrew Miner <notifications@github.com>
wrote:

> I'm confused, then. The change list you added to this comment thread
> seemed to clearly talk about new items added to the game (e.g., lenses and
> filters).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewminer/crafting-guide/pull/43#issuecomment-73398762>
> .
>



-- 
- Kamran Mackey

**Pull request closed without merging**
