### PR TITLE
EnderStorage 1.4.5.29

### PR DESCRIPTION
**Pull request by TiuTalk**
:+1:

### CODE REVIEW

**Comment by andrewminer** [comment]
Looks great, and I'd be happy to take this as-is, but there is one more thing you *could* add to make it even better.  Crafting Guide supports adding item descriptions and tutorial pages (see the [Assembly Table](http://local.crafting-guide.com:8000/browse/buildcraft/assembly_table/) and [Gates, Wires, and Chips](http://local.crafting-guide.com:8000/browse/buildcraft/tutorials/gates_wires_and_chips/)).  It would be extra awesome if you added a tutorial describing how to use various dyes to link everything together and some description text talking about how to use the Blue/Orange switch on the Ender Tank.

As I say, I'd be quite happy to take this as-is, so just let me know if you'd rather not.

**Comment by TiuTalk** [comment]
I will do the guides in a few hours!

**Comment by TiuTalk** [comment]
@andrewminer done!

**Comment by andrewminer** [comment]
All set!  You should see your change live on the website now.

**Comment by TiuTalk** [comment]
I'm not sure if there is something wrong.. but I'm seeing some duplicated mods there:

Imgur

It's an intermittent behaviour... sometimes they show up OK, sometimes they don't.. Maybe a cache?

**Comment by andrewminer** [comment]
Good catch, thanks!  I found the issue and fixed it.  Should be all better now.

**Pull request merged**
