### PR TITLE
Updated "More Blocks Mod" to "IDT"

### PR DESCRIPTION
**Pull request by MCE626**
I have updated it to my mod. Used to be called "More Blocks Mod" but now is "Industrial Technologies and More" or "IDT" for short.
I think i got down all the recipes from the mod, so yeah.
Also, my mod right now are on snapshot versions (Not mc snapshots), so this will be updated a lot before the full release of Beta 2.0 (Mod version)

### CODE REVIEW

**Comment by andrewminer** [comment]
Thanks for the contribution!  Unfortunately, it looks like you're missing a few things:

1. You'll need to add images for each item in your mod.
2. You'll need a 160x160 icon to represent your mod as a whole.
3. I got a number of errors while attempting to run the site with your data files.

I'd recommend you check out [these instructions](https://github.com/andrewminer/crafting-guide/wiki/Adding-support-for-a-new-Mod) for creating all the necessary files and doing some local testing.  Feel free to submit additional commits to this branch, and they'll automatically become part of the pull request.  Let me know once you're ready, and I'll give it another try on my end.

**Comment by MCE626** [comment]
I have a question. So i looked at some of the other mods, and they have this "index.html". Is that the same every time? I just noticed it so now i have to go back to each one i've already made and add it...

**Comment by andrewminer** [comment]
No, don't worry about the `index.html`.  I have a process which auto-generates those.  The website doesn't actually need them, but they're necessary to allow Google to index things properly.

**Comment by andrewminer** [comment]
You also don't need to commit on *every single file*.  Just go ahead and make all the changes which make sense for a full piece of work and submit everything together.  Otherwise, the commit history gets really messy with repetitive messages.

**Comment by MCE626** [comment]
oh.. yeah that's probably a better idea.. also, i just noticed now too i don't think i'm doing the images right..

**Comment by andrewminer** [comment]
You shouldn't have to do anything at all with the images if you're following the documentation.  The NEI dump and convert script will wind up putting the in the correct place.

**Comment by MCE626** [comment]
oooh, i think i get it now. So i do all the file stuff and just have an actual .png file where they need to be, then when i upload all together on here the .pngs are still pictures.... i was wondering how the others got images on here.

**Comment by andrewminer** [comment]
That sounds about right.  The only files you should need to create are the `mod.cg`, `mod-version.cg`, and, if you want, the `item.cg` files for each item (but those are optional).  For images, you should get most of them just by running the convert script, but you do need to provide the mod's `icon.png` file yourself.

**Comment by MCE626** [comment]
Ok, i think i got everything fixed and done now.

**Comment by MCE626** [comment]
Wait.. i don't remember closing this.. but i reopened it i think.

**Comment by MCE626** [comment]
I'm gonna have a new snapshot released soon, so this will be updated when i do that, just a heads up

**Comment by MCE626** [comment]
Don't upload it to the site, upon editing my wiki, i used the file for some crafting recipe references, and i noticed some where wrong that i didn't catch. i have to update it sometime...

**Pull request closed without merging**
