### PR TITLE
Add Forestry 3.4.0.7

### PR DESCRIPTION
**Pull request by sheldongriffin**

### CODE REVIEW

**Comment by andrewminer** [comment]
Incredible!  I can't thank you enough for taking on this huge mod... it's easy to lose track of how many items it adds because you don't really see that many in the game too often.

I've found a few bugs (ha ha) so far.  One that seems to come up a bunch is really my fault.  Since you started on this mod, I made a change to how recipes are handled internally, and, as a consequence, there are now a bunch of duplicates.  Basically, you should only ever list a recipe once.  If it happens to produce `extras`, then the system will figure things out on its own with just the single recipe, and if you add the recipe under the other item as well, then you'll get two.  I've removed a bunch of these locally, but there may be more.

A second is that I've found a few missing images:
* builder_s_woven_backpack.png
* postmanitem_rhetenor_blue_morpho__serum.png

Also, a missing item:
* Pulsating Propolis

In any case, I'm going to merge these into a `sheldongriffin-forestry` branch, and we can make whatever final fixes there before pushing it up live.  I'd recommend you grab my latest code for the site, and then we both spend a while browsing through a local version to check for any other missing pieces / duplicate recipes.  I'll push any fixes I make to that branch, and you can submit PR against that branch as well.  Once we're both satisfied, I'll deploy it.

Thanks *SO* much for putting in all the work on this!

**Comment by andrewminer** [comment]
I'll close this PR now that I've got the changes in the branch I mentioned.  I'll merge that one into my master when everything is buttoned up.

**Comment by andrewminer** [comment]
No recipe for liquid glass?

**Comment by andrewminer** [comment]
Missing item: Bronze Nugget

**Comment by andrewminer** [comment]
This recipe for Bronze Ingot seems confusing:

image

Is there supposed to be some kind of tool involved here?

**Comment by andrewminer** [comment]
I believe the Pipette should use Glass Pane rather than plain Glass.

**Comment by andrewminer** [comment]
For all the Crated things, I'm assuming you had to leave out the requirement for a crate because there isn't a place for it.  I'll update the issue in Trello related to allowing more slots to mention it.

**Comment by andrewminer** [comment]
Shouldn't there be recipes which use the various circuit boards?  Or does the current version of Forestry only use them as upgrades?

**Comment by andrewminer** [comment]
Okay.. I think that's all I can find.  Well done!  I'll push up the few things I just fixed on my own, and once the rest is fixed, I'll push everything up to the site.

**Comment by sheldongriffin** [comment]
I don't think they're really applicable as crafting parts; they're more like, say, the dark steel ball in EnderIO.

**Comment by sheldongriffin** [comment]
That's correct. Though, relatedly, there were some recipes (I don't recall which atm) where I did have room to specify the fuel but it would have muddied the waters - say, all the center slots were full.. How would you know the seed oil in the bottom right corner was fuel and not a recipe ingredient?

**Comment by sheldongriffin** [comment]
I think the Bronze Nugget may have been a copy a paste error.. I don't see any bronze nuggets in NEI for forestry.

**Comment by sheldongriffin** [comment]
Liquid Glass doesn't show a recipe in NEI. According to this http://forum.feed-the-beast.com/threads/liquid-glass.7316/ , it's made in the Thermionic Fabricator, which I just confirmed in creative, but it also says you can't actually remove it from the fabricator. The recipe for putting it in a bucket in the bottler seems to go against that though. If we do add a recipe for it, it's 1 piece of sand in the fabricator, and that's it. (No fuel, it's powered)

**Comment by sheldongriffin** [comment]
Pulsating propolis may be semi-removed. According to this http://feed-the-beast.wikia.com/wiki/Pulsating_Propolis it's made from a mysterious comb in a centrifuge, but no mysterious comb shows up in NEI. The Ender bees do show up, but I'm not sure how to use them to test if they make the comb. I'll see if I can figure out how to actually use the bees..

**Comment by andrewminer** [comment]
> I don't think [circuit boards are] really applicable

Got it.  I noticed in the docs that there was some confusion on that point.  In one place it said they were used as parts for building things, and in other places it seemed to indicate they were just for making upgrades.

> there were some recipes (I don't recall which atm) where I did have room to specify the fuel but it would have muddied the waters

I think that's the right call for now.  Once I expand things to allow for more slots, it will need to be re-visited.

> If we do add a recipe for it

I'd say to go ahead.  Otherwise, the crafting plans for things which need it will just list it as a raw material.

> it's made from a mysterious comb

Ah... I remember now.  The Ender Bees do produce a comb which can, it turn, be centrifuged to produce it.

**Pull request closed without merging**
